name: Testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Build models
      env:
        SECRET_KEY: ly97e#bh!*%8!*=u7jumec3uiq&-g^k8^sygkrd&(vnb#df^$%
      run: |
        python3 manage.py makemigrations
        python3 manage.py migrate
    - name: Run Tests
      env:
        SECRET_KEY: ly97e#bh!*%8!*=u7jumec3uiq&-g^k8^sygkrd&(vnb#df^$%
      run: |
        python3 manage.py test
